### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cideM** [tami5/compe-conjure#2]
The README states to call `attach` but that function doesn't exist anymore in the source, it seems. Also the `ftplugin/after` file has `packadd conjure` hardcoded. I think it's better to let the user handle this since depending on how you install plugins it could also be called something else entirely

**Comment by tami5** [comment]
Hey @cideM , valid points, thanks for sharing them. It has been reflected in https://github.com/tami5/compe-conjure/commit/809853ff8098dffcf8ba5ac89bcf07806eb8f981.

Please check if it works for you now

**Comment by cideM** [comment]
Amazing that was quick, works perfectly!
